package:
  name: prettier
  version: 3.8.1
  epoch: 0
  checks:
    disabled:
      - usrlocal
  dependencies:
    runtime:
      - nodejs
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - build-base
      - ca-certificates-bundle
      - nodejs
      - npm
      - simdjson

pipeline:
  - uses: npm/install
    with:
      package: ${{package.name}}
      version: ${{package.version}}
