package:
  name: hadolint
  version: 2.14.0
  epoch: 0
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    # https://github.com/hadolint/hadolint/blob/0d4f787e3f8211457c4423febc24680a313c43d0/.github/workflows/release.yml#L47-L52
    packages:
      - bash
      - binutils-gold
      - cabal
      - ca-certificates-bundle
      - curl
      - g++
      - gcc
      - git
      - gmp
      - gmp-dev
      - gmp-static
      - gzip
      - libc-dev
      - libffi-dev
      - make
      - musl-dev
      - ncurses-dev
      - ncurses-static
      - perl
      - tar
      - xz
      - zlib
      - zlib-dev
      - zlib-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hadolint/hadolint.git
      tag: v${{package.version}}
      expected-commit: 57e1618d78fd469a92c1e584e8c9313024656623
  - runs: |
      # https://github.com/Homebrew/homebrew-core/blob/9d824ec719cb59697557fb3c5541bdfc61e22933/Formula/h/hadolint.rb#L25-L33
      cabal v2-update
      cabal v2-install \
        --install-method=copy \
        --installdir=${{targets.destdir}}/usr/bin \
        --allow-newer=base,containers,template-haskell \
        --verbose
  - uses: strip
