package:
  name: hadolint
  version: 2.12.1-beta
  epoch: 0
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - ca-certificates-bundle
      - cabal
      - git

pipeline:
  - uses: fetch
    with:
      expected-sha256: b9461721f689f90e3b1aa691bbf80daaf8bc7e876ba910c45a98b641d9f9dfc2
      uri: https://github.com/hadolint/hadolint/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      cabal configure
      cabal update
      cabal build
      ls -lash

  - uses: strip
