package:
  name: hadolint
  version: 2.12.0
  epoch: 0
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - ca-certificates-bundle
      - cabal
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hadolint/hadolint.git
      tag: v${{package.version}}
      expected-commit: b3555ba9c2bfd9401e79f2f0da68dd1ae38e10c7
  - runs: |
      cabal v2-update
      cabal v2-install
      ls -lash

  - uses: strip
