package:
  name: hadolint
  version: 2.13.1
  epoch: 0
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - ca-certificates-bundle
      - cabal
      - git
      - musl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hadolint/hadolint.git
      tag: v${{package.version}}-beta
      expected-commit: 4ab5d7809325c8de23956a44ca5a1f3c25907faf
  - runs: |
      # Reference:
      # - https://github.com/Homebrew/homebrew-core/blob/d7b00fd733bcf99f55a20942cf980ff045f41478/Formula/h/hadolint.rb#L28-L29
      # - https://github.com/hadolint/hadolint/blob/742b76e3b9b4d45d6716771b0f1fae2fa0069104/release.nix#L29-L37
      cabal v2-update
      cabal v2-install \
        --max-backjumps=-1 \
        --install-method=copy \
        --installdir=${{targets.destdir}}/usr/bin \
        --disable-executable-dynamic \
        --disable-shared \
        --disable-library-for-ghci \
        --disable-profiling \
        --disable-debug-info \
        --disable-coverage \
        --verbose
  - uses: strip
