name: Build
on:
  workflow_call:
    inputs:
      owner:
        description: 'Repository owner'
        required: true
        type: string
      image:
        description: 'Image to be built'
        required: true
        type: string
      tag:
        description: 'Tag to be used for the image'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build image
        uses: distroless/actions/apko-build@main
        with:
          config: images/${{ inputs.image }}/${{ inputs.image }}.apko.yaml
          tag: ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.tag }}
