name: debug
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'
      - 'debug/**'
  pull_request:
    paths:
      - '.github/workflows/debug.yml'
      - 'debug/**'
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml
    with:
      owner: ${{ github.repository_owner }}
      image: debug
      tag: pr-${{ github.event.pull_request.head.sha }}
  publish:
    permissions:
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/publish.yml
    with:
      owner: ${{ github.repository_owner }}
      image: debug
      tag: ${{ github.ref_name }}-1.${{ github.run_number }}.${{ github.run_attempt }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
