name: Build (& Publish) / envsubst
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
  pull_request:
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build image
        uses: distroless/actions/apko-build@main
        with:
          archs: amd64,arm64
          config: envsubst/envsubst.apko.yaml
          tag: ghcr.io/hpedrorodrigues/envsubst:${{ github.ref_name }} ghcr.io/hpedrorodrigues/envsubst:latest
  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish image
        uses: distroless/actions/apko-publish@main
        with:
          archs: amd64,arm64
          config: envsubst/envsubst.apko.yaml
          tag: ghcr.io/hpedrorodrigues/envsubst:${{ github.ref_name }} ghcr.io/hpedrorodrigues/envsubst:latest
