name: envsubst
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml
    with:
      owner: ${{ github.repository_owner }}
      image: envsubst
      tag: pr-${{ github.event.pull_request.head.sha }}
  publish:
    permissions:
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/publish.yml
    with:
      owner: ${{ github.repository_owner }}
      image: envsubst
      tag: 1.${{ github.run_number }}.${{ github.run_attempt }}
      revision: ${{ github.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
