name: envsubst
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
  pull_request:
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml
    with:
      owner: ${{ github.repository_owner }}
      image: envsubst
  publish:
    permissions:
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/publish.yml
    with:
      owner: ${{ github.repository_owner }}
      image: envsubst
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
