name: prettier
on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/prettier.yml'
      - 'prettier/**'
  pull_request:
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/prettier.yml'
      - 'prettier/**'
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_shared_build.yml
    with:
      owner: ${{ github.repository_owner }}
      image: prettier
      version: pr-${{ github.event.pull_request.head.sha }}
      melange_package: true
  publish:
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_shared_publish.yml
    with:
      owner: ${{ github.repository_owner }}
      image: prettier
      version: 1.${{ github.run_number }}.${{ github.run_attempt }}
      revision: ${{ github.sha }}
      melange_package: true
    secrets:
      gcr_token: ${{ secrets.GITHUB_TOKEN }}
