name: prettier
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/prettier.yml'
      - 'images/prettier/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/prettier.yml'
      - 'images/prettier/**'
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml
    with:
      owner: ${{ github.repository_owner }}
      image: prettier
      tag: pr-${{ github.event.pull_request.head.sha }}
  publish:
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/publish.yml
    with:
      owner: ${{ github.repository_owner }}
      image: prettier
      tag: 1.${{ github.run_number }}.${{ github.run_attempt }}
      revision: ${{ github.sha }}
    secrets:
      docker_hub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      gcr_token: ${{ secrets.GITHUB_TOKEN }}
