name: Publish
on:
  workflow_call:
    inputs:
      owner:
        description: 'Repository owner'
        required: true
        type: string
      image:
        description: 'Image to be built'
        required: true
        type: string
      tag:
        description: 'Tag to be used for the image'
        required: true
        type: string
      revision:
        description: 'Revision to be used for the image'
        required: true
        type: string
    secrets:
      docker_hub_token:
        description: 'Access Token to be used to push to Docker Hub'
        required: true
      gcr_token:
        description: 'Personal Access Token to be used to push to GitHub Container Registry'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Get current date
        run: echo "CURRENT_DATE=$(TZ=UTC date +%Y-%m-%dT%H:%M:%S)" >> ${GITHUB_ENV}
      - name: Publish image (${{ inputs.image }}) to GitHub Container Registry
        uses: hpedrorodrigues/chainguard-actions/apko-publish@main
        with:
          config: ${{ inputs.image }}/${{ inputs.image }}.apko.yaml
          tag: ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.tag }} ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:latest
          generic-user: ${{ inputs.owner }}
          generic-pass: ${{ secrets.gcr_token }}
          annotations: org.opencontainers.image.revision:${{ inputs.revision }},org.opencontainers.image.created:${{ env.CURRENT_DATE }},org.opencontainers.image.version:${{ inputs.tag }}
      - name: Publish image (${{ inputs.image }}) to Docker Hub
        uses: hpedrorodrigues/chainguard-actions/apko-publish@main
        with:
          config: ${{ inputs.image }}/${{ inputs.image }}.apko.yaml
          tag: docker.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.tag }} docker.io/${{ inputs.owner }}/${{ inputs.image }}:latest
          generic-user: ${{ inputs.owner }}
          generic-pass: ${{ secrets.docker_hub_token }}
          annotations: org.opencontainers.image.revision:${{ inputs.revision }},org.opencontainers.image.created:${{ env.CURRENT_DATE }},org.opencontainers.image.version:${{ inputs.tag }}
