name: Publish
on:
  workflow_call:
    inputs:
      owner:
        description: 'Repository owner'
        required: true
        type: string
      image:
        description: 'Image to be built'
        required: true
        type: string
      tag:
        description: 'Tag to be used for the image'
        required: true
        type: string
    secrets:
      token:
        description: 'Personal Access Token to be used to push to registries'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.owner }}
          password: ${{ secrets.token }}
      - name: Publish image (${{ inputs.image }})
        uses: distroless/actions/apko-publish@main
        with:
          config: ${{ inputs.image }}/${{ inputs.image }}.apko.yaml
          tag: ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.tag }} ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:latest
