name: Build
on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      image:
        required: true
        type: string
      version:
        required: true
        type: string
      melange_package:
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup QEMU
        if: ${{ inputs.melange_package }}
        uses: docker/setup-qemu-action@v3
      - name: Build package
        uses: chainguard-dev/actions/melange-build@main
        if: ${{ inputs.melange_package }}
        with:
          sign-with-temporary-key: true
          config: images/${{ inputs.image }}/${{ inputs.image }}.melange.yaml
          repository-path: ${{ github.workspace }}/images/${{ inputs.image }}/packages
          archs: x86_64,aarch64
      - name: Build image
        uses: distroless/actions/apko-build@main
        with:
          config: images/${{ inputs.image }}/${{ inputs.image }}.apko.yaml
          tag: ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.version }}
          repository-append: ${{ github.workspace }}/images/${{ inputs.image }}/packages
          keyring-append: ${{ inputs.melange_package && format('{0}/melange.rsa.pub', github.workspace) || '' }}
